### ISSUE TITLE
Python: Missing README

### ISSUE THREAD

**Issue by mrhso** [Artoria2e5/PRCoords#9]
```
$ pip install prcoords
Collecting prcoords
  Using cached https://files.pythonhosted.org/packages/e5/60/7b484bee55a21a0ca6392eef3f75c28f11e682ba8731c6ea93764c24adba/prcoords-1.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/data/data/com.termux/files/usr/tmp/pip-install-1pmlg7ru/prcoords/setup.py", line 5, in <module>
        with open("../README.md", "r") as f:
    FileNotFoundError: [Errno 2] No such file or directory: '../README.md'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-install-1pmlg7ru/prcoords/
```

**Comment by Artoria2e5** [comment]
Yep, happens with tarball install. Can you confirm that 8336543 fixes the issue (test by only getting the `py` directory)?

**Comment by mrhso** [comment]
It works.

**Comment by Artoria2e5** [comment]
did a force push (lmao) and uploaded to pypi.
